name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: read
  pull-requests: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Generate cache key
        id: cache-key
        run: echo "key=pnpm-${{ hashFiles('pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript check
        run: pnpm typecheck

  peer-deps:
    name: Peer Dependency Integrity
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            pnpm-

      - name: Strict peer dependency install
        # This will fail fast if previously masked peer issues exist due to hoisting config
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: List unmet peer dependencies (if any)
        run: pnpm list --depth=999 || true

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      DATABASE_URL: "file:./test.db"
      NEXTAUTH_SECRET: "test-secret-for-ci"
      NEXTAUTH_URL: "http://localhost:3000"
      RESEND_API_KEY: "re_dummy_api_key_for_test"
      EMAIL_FROM: "noreply@example.com"
      GOOGLE_CLIENT_ID: "dummy_client_id"
      GOOGLE_CLIENT_SECRET: "dummy_client_secret"
      NODE_ENV: "test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Run database migrations
        run: pnpm db:push

      - name: Seed test database
        run: pnpm db:seed

      - name: Run tests
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    # Only build if quality gates passed (explicitly include setup for cache key access)
    needs: [setup, lint, test, peer-deps]
    env:
      DATABASE_URL: "file:./build.db"
      NEXTAUTH_SECRET: "build-secret-for-ci"
      NEXTAUTH_URL: "http://localhost:3000"
      RESEND_API_KEY: "re_dummy_api_key_for_build"
      EMAIL_FROM: "noreply@example.com"
      GOOGLE_CLIENT_ID: "dummy_client_id"
      GOOGLE_CLIENT_SECRET: "dummy_client_secret"
      NODE_ENV: "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Setup build database
        run: pnpm db:push

      - name: Build application
        run: pnpm build

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for known vulnerabilities
        run: npx audit-ci --moderate

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [lint, peer-deps, test, build, security]
    if: always()
    steps:
      - name: Summarize results
        run: |
          echo "Lint: ${{ needs.lint.result }}"
          echo "Peer Deps: ${{ needs.peer-deps.result }}"
          echo "Tests: ${{ needs.test.result }}"
          echo "Build: ${{ needs.build.result }}"
          echo "Security: ${{ needs.security.result }}"
          if [ "${{ needs.lint.result }}" != "success" ] || [ "${{ needs.peer-deps.result }}" != "success" ] || [ "${{ needs.test.result }}" != "success" ] || [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.security.result }}" != "success" ]; then
            echo "One or more jobs failed."; exit 1; fi
